# Generated by Django 5.2.4 on 2025-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.TextField()),
                ('grade', models.TextField()),
                ('date_set', models.TextField()),
                ('date_strip', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('open', models.IntegerField()),
            ],
            options={
                'db_table': 'Wall',
                'managed': False,
            },
        ),
    ]
